---
# CE2 specific configurations
router_config:
  interfaces:
    ethernet:
      eth0:
        description: "Management Interface"
        address: "192.168.100.135/24"
      eth1:
        description: "To PE2"
        address: "10.0.5.2/30"
  protocols:
    ospf:
      area:
        "0":
          network: "10.0.5.0/30"
    static:
      route:
        "0.0.0.0/0":
          next_hop: "192.168.100.1"
