---
# CE2 Customer Edge Router - Based on working L3VPN example
router_config:
  router_id: "172.16.0.6"
  interfaces:
    ethernet:
      eth0:
        description: "Management Interface"
        address: "192.168.100.16/24"
      eth1:
        description: "To PE2"
        address: "172.16.0.6/30"
    loopback:
      lo:
        description: "Customer LAN - Site 2"
        address: "10.0.2.1/24"
  protocols:
    bgp:
      asn: "65002"
      neighbors:
        "172.16.0.5":
          remote_as: "65000"
          description: "eBGP to PE2"
          address_family:
            - "ipv4-unicast"
      address_family:
        ipv4_unicast:
          networks:
            - "10.0.2.0/24"
    static:
      route:
        "0.0.0.0/0":
          next_hop: "192.168.100.1"
